[build-system]
requires = ["maturin>=1.15.0,<2.0"]
build-backend = "maturin"

[project]
name = "speedy"
version = "0.0.1"
authors = [
    { name = "Alexander Kuzmin", email = "qrer71@yandex.ru" },
    { name = "Alexander Kuzmin", email = "funks.1@yandex.ru" }
]
license = { file = "LICENSE" }
description = "In development"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "anyio>=4.15.1",
    "covdefaults>=2.3.0",
    "typing-extensions",
]

[project.optional-dependencies]
dev = [
    "pytest<=9.1.1",
    "httpx<=0.28.1",
    "pytest-cov",
    "pytest-asyncio<=1.4.0",
    "tox>=4.61.3",
    "trio<=0.34.0",
    "ruff>=0.16.6",
    "pytest-mock>=3.15.1",
]

[tool.maturin]
python-source = "python"
module-name = "speedy._speedy"

[tool.tox]
requires = ["tox>=4.61.3", "tox-uv>=0.11.0"]
env_list = ["3.12", "3.13", "3.14"]

[tool.tox.env_run_base]
description = "Run test under {base_python}"
extras = ["dev"]
commands = [["pytest"]]

[project.urls]
"Homepage" = "https://github.com/WolfMTK/speedy"
"Repository" = "https://github.com/WolfMTK/speedy"

[tool.coverage.run]
concurrency = ["multiprocessing", "thread"]
omit = ["*/tests/*"]
parallel = true
plugins = ["covdefaults"]
source = ["speedy"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "error",
    "ignore::UserWarning",
    'ignore:function ham\(\) is deprecated:DeprecationWarning',
]

[tool.ruff]
target-version = "py312"
line-length = 120
extend-exclude = ["tests"]

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "UP",
    "B",
    "C4",
    "SIM",
    "RUF",
]
ignore = [
    "E203",
]

[tool.ruff.format]
quote-style = "double"
