from typing import Protocol


# TODO: add specific arguments when implementing an application class
class BaseHTTPMethods(Protocol):
    def get(self, *args, **kwargs): ...

    def post(self, *args, **kwargs): ...

    def delete(self, *args, **kwargs): ...

    def patch(self, *args, **kwargs): ...

    def put(self, *args, **kwargs): ...

    def head(self, *args, **kwargs): ...

    def trace(self, *args, **kwargs): ...

    def options(self, *args, **kwargs): ...
