name: Test

on:
  push:
    branches:
      - "main"
      - "master"
# TODO: Uncomment after the application has been created
      - "dev"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
      - name: "Install uv"
        uses: "astral-sh/setup-uv@v7"
      - name: "Install dependencies"
        run: uv sync --extra dev
      - name: "Run tests"
        run: uv run tox
