name: Test

on:
  push:
    branches:
      - "main"
      - "master"
# TODO: Uncomment after the application has been created
      - "dev"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Install dependencies"
        run: |
          uv sync --extra dev && uv run tox
      - name: "Run tests"
        run: "python -m pytest"
